In [1]:
import pandas as pd

# Load the population data
population_df = pd.read_csv('../data/curated/forecasted_populations.csv')

# Extract only the relevant columns for 2025, 2026, and 2027
population_df = population_df[['Code', '2025_Forecast', '2026_Forecast', '2027_Forecast']]

# Rename columns for easier merging
population_df.columns = ['SA2_CODE21', 'pop_2025', 'pop_2026', 'pop_2027']

In [2]:
# Load the population data
crime_df = pd.read_parquet('../data/curated/crime_data_with_predictions.parquet')

# Extract only the relevant columns for 2025, 2026, and 2027
crime_df = crime_df[['SA2_ID', '2025', '2026', '2027']]

# Rename columns for easier merging
crime_df.columns = ['SA2_CODE21', 'crime_2025', 'crime_2026', 'crime_2027']

crime_df['SA2_CODE21'] = crime_df['SA2_CODE21'].astype('float')

In [3]:
crime_df.head()

    SA2_CODE21  crime_2025  crime_2026  crime_2027
0  206011106.0  820.581478  843.299306  866.763845
1  206011107.0  832.314597  832.694978  833.828636
2  206011109.0  587.676228  587.717975  588.461329
3  206011495.0  751.259716  751.603053  752.626311
4  206011496.0  757.494707  757.840894  758.872643

In [4]:
population_df.head()

  SA2_CODE21  pop_2025  pop_2026  pop_2027
0  206011106     14477     14871     15264
1  206011107     14684     14684     14684
2  206011109     10368     10364     10363
3  206011495     13254     13254     13254
4  206011496     13364     13364     13364

In [5]:

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Load your training data
df = pd.read_parquet('../data/curated/model_data.parquet')  # Replace with your actual data loading method

# Calculate average distances and other relevant statistics for each SA2 code
sa2_stats = df.groupby('SA2_CODE21').agg({
    'distance_to_bus_stop': 'mean',
    'distance_to_train_stop': 'mean',
    'distance_to_tram_stop': 'mean',
    'distance_to_hospital': 'mean',
    'distance_to_mall': 'mean',
    'distance_to_park': 'mean',
    'distance_to_supermarket': 'mean',
    'distance_to_CBD': 'mean',
    'distance_to_school': 'mean',
    'distance_to_uni': 'mean',
}).reset_index()

# Define realistic feature combinations
# Each tuple represents (bedrooms, bathrooms, carspaces)
valid_combinations = [
    (1, 1, 1), (1, 1, 0),
    (2, 1, 1), (2, 1, 0), (2, 2, 1), (2, 2, 0),
    (3, 1, 1), (3, 1, 0), (3, 2, 1), (3, 2, 0)
]

# Years for prediction
years = [2025, 2026, 2027]

# Create an empty DataFrame to store the test data
test_data = pd.DataFrame()

# Define the reference date
reference_date = pd.Timestamp('2011-01-01')

# Define probabilities for is_furnished
furnished_probs = [0.5, 0.5]

crime_df['SA2_CODE21'] = crime_df['SA2_CODE21'].astype('int')
sa2_stats['SA2_CODE21'] = sa2_stats['SA2_CODE21'].astype('int')
population_df['SA2_CODE21'] = pd.to_numeric(population_df['SA2_CODE21'], errors='coerce')

# Create the test data
for sa2_code in sa2_stats['SA2_CODE21']:
    for bedrooms, bathrooms, carspaces in valid_combinations:
        for year in years:
            # Get the average distances for the current SA2 code
            avg_distances = sa2_stats[sa2_stats['SA2_CODE21'] == sa2_code].iloc[0]

            # Define the middle of the year (July 1)
            middle_of_year = datetime(year, 7, 1)

            # Calculate the number of days since the reference date
            date_numeric = (middle_of_year - reference_date).days

            # Generate is_furnished with 50/50 chance
            is_furnished = 0

            # Create bed_bath_interaction feature
            bed_bath_interaction = bedrooms * bathrooms
            

            # Create a DataFrame for each combination
            temp_df = pd.DataFrame({
                'SA2_CODE21': [sa2_code],
                'bedrooms': [bedrooms],
                'bathrooms': [bathrooms],
                'year': [year],
                'distance_to_bus_stop': [avg_distances['distance_to_bus_stop']],
                'distance_to_train_stop': [avg_distances['distance_to_train_stop']],
                'distance_to_tram_stop': [avg_distances['distance_to_tram_stop']],
                'distance_to_hospital': [avg_distances['distance_to_hospital']],
                'distance_to_mall': [avg_distances['distance_to_mall']],
                'distance_to_park': [avg_distances['distance_to_park']],
                'distance_to_supermarket': [avg_distances['distance_to_supermarket']],
                'distance_to_CBD': [avg_distances['distance_to_CBD']],
                'distance_to_school': [avg_distances['distance_to_school']],
                'distance_to_uni': [avg_distances['distance_to_uni']],
                'population': [population_df.loc[population_df['SA2_CODE21'] == sa2_code, f'pop_{year}'].values[0]],
                'date_numeric': [date_numeric],
                'bed_bath_interaction': [bed_bath_interaction],
                'carspaces': [carspaces],
                'is_furnished': [is_furnished],
                'crime': [crime_df.loc[crime_df['SA2_CODE21'] == sa2_code, f'crime_{year}'].values[0]],
            })

            # Append to the main DataFrame
            test_data = pd.concat([test_data, temp_df], ignore_index=True)

# Save to CSV or use directly
test_data.to_csv('../data/curated/test_data.csv', index=False)

print("Test data generation complete.")
print(test_data.head())

Test data generation complete.
   SA2_CODE21  bedrooms  bathrooms  year  distance_to_bus_stop  \
0   201011006         1          1  2025              0.741864
1   201011006         1          1  2026              0.741864
2   201011006         1          1  2027              0.741864
3   201011006         1          1  2025              0.741864
4   201011006         1          1  2026              0.741864

   distance_to_train_stop  distance_to_tram_stop  distance_to_hospital  \
0                 0.91511               1.091632              0.036647
1                 0.91511               1.091632              0.036647
2                 0.91511               1.091632              0.036647
3                 0.91511               1.091632              0.036647
4                 0.91511               1.091632              0.036647

   distance_to_mall  distance_to_park  distance_to_supermarket  \
0          0.007196           0.00017                 0.008238
1          0.007196           0.00017                 0.008238
2          0.007196           0.00017                 0.008238
3          0.007196           0.00017                 0.008238
4          0.007196           0.00017                 0.008238

   distance_to_CBD  distance_to_school  distance_to_uni  population  \
0         1.188191             0.03149         1.178579       15294
1         1.188191             0.03149         1.178579       16366
2         1.188191             0.03149         1.178579       17341
3         1.188191             0.03149         1.178579       15294
4         1.188191             0.03149         1.178579       16366

   date_numeric  bed_bath_interaction  carspaces  is_furnished        crime
0          5295                     1          1             0  1210.912850
1          5660                     1          1             0  1290.087583
2          6025                     1          1             0  1366.340312
3          5295                     1          0             0  1210.912850
4          5660                     1          0             0  1290.087583

In [6]:
print(crime_df.dtypes)  # Check data types in crime_df
print(type(sa2_code))   # Check the type of sa2_code
print(population_df.dtypes)

SA2_CODE21      int64
crime_2025    float64
crime_2026    float64
crime_2027    float64
dtype: object
<class 'int'>
SA2_CODE21    float64
pop_2025        int64
pop_2026        int64
pop_2027        int64
dtype: object

In [7]:



# Print the number of unique SA2_CODE21 values in each DataFrame
print(f"Number of unique SA2_CODE21 in sa2_stats: {sa2_stats['SA2_CODE21'].nunique()}")
print(f"Number of unique SA2_CODE21 in crime_df: {crime_df['SA2_CODE21'].nunique()}")

# Check the intersection of SA2_CODE21 values
matching_sa2 = set(sa2_stats['SA2_CODE21']).intersection(set(crime_df['SA2_CODE21']))
print(f"Number of matching SA2_CODE21 values: {len(matching_sa2)}")

# Check the SA2_CODE21 values that are in sa2_stats but not in crime_df
missing_in_crime = set(sa2_stats['SA2_CODE21']).difference(set(crime_df['SA2_CODE21']))
print(f"Number of SA2_CODE21 values in sa2_stats but not in crime_df: {len(missing_in_crime)}")

# Check the SA2_CODE21 values that are in crime_df but not in sa2_stats
missing_in_sa2_stats = set(crime_df['SA2_CODE21']).difference(set(sa2_stats['SA2_CODE21']))
print(f"Number of SA2_CODE21 values in crime_df but not in sa2_stats: {len(missing_in_sa2_stats)}")

# Optionally, print the actual missing values if needed
print("SA2_CODE21 values in sa2_stats but not in crime_df:", missing_in_crime)
print("SA2_CODE21 values in crime_df but not in sa2_stats:", missing_in_sa2_stats)

Number of unique SA2_CODE21 in sa2_stats: 384
Number of unique SA2_CODE21 in crime_df: 603
Number of matching SA2_CODE21 values: 384
Number of SA2_CODE21 values in sa2_stats but not in crime_df: 0
Number of SA2_CODE21 values in crime_df but not in sa2_stats: 219
SA2_CODE21 values in sa2_stats but not in crime_df: set()
SA2_CODE21 values in crime_df but not in sa2_stats: {204031491, 204031492, 21001, 21002, 21003, 21004, 21005, 203031049, 20501, 20502, 20503, 20504, 20505, 209031210, 204011054, 204011055, 204011056, 204011057, 204011058, 204011059, 204011060, 204011061, 204011062, 215011386, 215011388, 215011389, 215011390, 215011391, 215011392, 215011393, 215011394, 217041477, 217041478, 217041479, 217041480, 201021009, 201021010, 201021011, 201021012, 210011227, 204031068, 204031069, 204031070, 204031071, 204031072, 21601, 21602, 204031075, 21603, 204031073, 215031400, 215031401, 215031402, 215031403, 215031404, 21101, 21102, 21103, 21104, 21105, 215031405, 20601, 20602, 20603, 20604, 20605, 20606, 20607, 205011077, 205011078, 20101, 20102, 20103, 216011406, 216011407, 216011408, 216011409, 216011410, 202021026, 202021027, 202021028, 202021029, 202021030, 202021031, 205031087, 210051248, 205031088, 205031089, 205031090, 205031091, 205031093, 205031092, 216031415, 216031416, 216031418, 216031419, 21701, 21703, 21704, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 21201, 216, 21202, 21203, 21204, 21205, 20701, 20702, 20703, 217011420, 205051099, 205051100, 205051101, 205051102, 205051103, 205051104, 217011422, 217011423, 20201, 20202, 20203, 217011421, 201011481, 201011482, 201011484, 217031471, 217031472, 217031473, 217031474, 217031475, 217031476, 21301, 21302, 21303, 21304, 21305, 201011001, 201011002, 201011005, 201011007, 201011008, 20801, 20802, 20803, 20804, 204021063, 204021064, 204021065, 204021066, 204021067, 20301, 20302, 20303, 215021395, 215021396, 205041493, 205041494, 215021398, 215021399, 201031013, 201031014, 201031015, 201031016, 216031593, 216031594, 201031017, 210021233, 210021234, 202011018, 202011019, 202011020, 202011021, 202011022, 202011023, 202011024, 202011025, 205021080, 21401, 21402, 205021082, 205021083, 205021084, 205021086, 215021469, 215021470, 216021411, 216021412, 20901, 20902, 20903, 20904, 216021413, 20401, 20402, 20403, 202031032, 202031033, 205041094, 205041095, 205041096, 205041098, 208031184, 208031192, 21501, 21502, 21503}

In [8]:
# Print the number of unique SA2_CODE21 values in each DataFrame
print(f"Number of unique SA2_CODE21 in sa2_stats: {sa2_stats['SA2_CODE21'].nunique()}")
print(f"Number of unique SA2_CODE21 in population_df: {population_df['SA2_CODE21'].nunique()}")

# Check the intersection of SA2_CODE21 values
matching_sa2 = set(sa2_stats['SA2_CODE21']).intersection(set(population_df['SA2_CODE21']))
print(f"Number of matching SA2_CODE21 values: {len(matching_sa2)}")

# Check the SA2_CODE21 values that are in sa2_stats but not in population_df
missing_in_population = set(sa2_stats['SA2_CODE21']).difference(set(population_df['SA2_CODE21']))
print(f"Number of SA2_CODE21 values in sa2_stats but not in population_df: {len(missing_in_population)}")

# Check the SA2_CODE21 values that are in population_df but not in sa2_stats
missing_in_sa2_stats = set(population_df['SA2_CODE21']).difference(set(sa2_stats['SA2_CODE21']))
print(f"Number of SA2_CODE21 values in population_df but not in sa2_stats: {len(missing_in_sa2_stats)}")

# Optionally, print the actual missing values if needed
print("SA2_CODE21 values in sa2_stats but not in population_df:", missing_in_population)
print("SA2_CODE21 values in population_df but not in sa2_stats:", missing_in_sa2_stats)

Number of unique SA2_CODE21 in sa2_stats: 384
Number of unique SA2_CODE21 in population_df: 606
Number of matching SA2_CODE21 values: 384
Number of SA2_CODE21 values in sa2_stats but not in population_df: 0
Number of SA2_CODE21 values in population_df but not in sa2_stats: 224
SA2_CODE21 values in sa2_stats but not in population_df: set()
SA2_CODE21 values in population_df but not in sa2_stats: {2.0, 204031491.0, 204031492.0, 21001.0, 21002.0, 21003.0, 21004.0, 21005.0, 203031049.0, 20501.0, 20502.0, 20503.0, 20504.0, 20505.0, 209031210.0, 204011054.0, 204011055.0, 204011056.0, 204011057.0, 204011058.0, 204011059.0, 204011060.0, 204011061.0, 204011062.0, 215011386.0, 215011388.0, 215011389.0, 215011390.0, 215011391.0, 215011392.0, 215011393.0, 215011394.0, 217041477.0, 217041478.0, 217041479.0, 217041480.0, 201021009.0, 201021010.0, 201021011.0, 201021012.0, 210011227.0, 204031068.0, 204031069.0, 204031070.0, 204031071.0, 204031072.0, 21601.0, 21602.0, 204031075.0, 21603.0, 204031073.0, 215031400.0, 215031401.0, 215031402.0, 215031403.0, 215031404.0, 21101.0, 21102.0, 21103.0, 21104.0, 21105.0, 215031405.0, 20601.0, 20602.0, 20603.0, 20604.0, 20605.0, 20606.0, 20607.0, 205011077.0, 205011078.0, nan, 20101.0, 20102.0, 20103.0, 216011406.0, 216011407.0, 216011408.0, 216011409.0, 216011410.0, 202021026.0, 202021027.0, 202021028.0, 202021029.0, 202021030.0, 202021031.0, 205031087.0, 210051248.0, 205031088.0, 205031089.0, 205031090.0, 205031091.0, 205031093.0, 205031092.0, 216031415.0, 216031416.0, 216031418.0, 21204.0, 216031419.0, 21205.0, 21701.0, 21703.0, 21704.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0, 211.0, 212.0, 213.0, 214.0, 215.0, 216.0, 217.0, 21201.0, 21202.0, 21203.0, 20701.0, 20702.0, 20703.0, 217011420.0, 205051099.0, 205051100.0, 205051101.0, 205051102.0, 205051103.0, 205051104.0, 217011422.0, 217011423.0, 20201.0, 20202.0, 20203.0, 217011421.0, 201011481.0, 201011482.0, 201011484.0, 217031471.0, 217031472.0, 217031473.0, 217031474.0, 217031475.0, 217031476.0, 21301.0, 21302.0, 21303.0, 21304.0, 21305.0, 201011001.0, 201011002.0, 201011005.0, 201011007.0, 201011008.0, 20801.0, 20802.0, 20803.0, 20804.0, 204021063.0, 204021064.0, 204021065.0, 204021066.0, 204021067.0, 20301.0, 20302.0, 20303.0, 215021395.0, 215021396.0, 205041493.0, 205041494.0, 215021398.0, 215021399.0, 201031013.0, 201031014.0, 201031015.0, 201031016.0, 216031593.0, 216031594.0, 201031017.0, 210021233.0, 210021234.0, nan, 202011018.0, 202011019.0, 202011020.0, 202011021.0, 202011022.0, 202011023.0, 202011024.0, 202011025.0, 205021080.0, 21401.0, 21402.0, 205021082.0, 205021083.0, 205021084.0, 205021086.0, 215021469.0, 215021470.0, 216021411.0, 216021412.0, 20901.0, 20902.0, 20903.0, 20904.0, 216021413.0, 20401.0, 20402.0, 20403.0, 202031032.0, 202031033.0, 205041094.0, 205041095.0, 205041096.0, 205041098.0, 208031184.0, 208031192.0, 21501.0, 21502.0, 21503.0}

In [9]:
test_data.count()

SA2_CODE21                 11520
bedrooms                   11520
bathrooms                  11520
year                       11520
distance_to_bus_stop       11520
distance_to_train_stop     11520
distance_to_tram_stop      11520
distance_to_hospital       11520
distance_to_mall           11520
distance_to_park           11520
distance_to_supermarket    11520
distance_to_CBD            11520
distance_to_school         11520
distance_to_uni            11520
population                 11520
date_numeric               11520
bed_bath_interaction       11520
carspaces                  11520
is_furnished               11520
crime                      11520
dtype: int64

In [10]:
test_data.to_csv('../data/curated/test_data.csv', index=False)

In [11]:
print(test_data.head(20))

    SA2_CODE21  bedrooms  bathrooms  year  distance_to_bus_stop  \
0    201011006         1          1  2025              0.741864
1    201011006         1          1  2026              0.741864
2    201011006         1          1  2027              0.741864
3    201011006         1          1  2025              0.741864
4    201011006         1          1  2026              0.741864
5    201011006         1          1  2027              0.741864
6    201011006         2          1  2025              0.741864
7    201011006         2          1  2026              0.741864
8    201011006         2          1  2027              0.741864
9    201011006         2          1  2025              0.741864
10   201011006         2          1  2026              0.741864
11   201011006         2          1  2027              0.741864
12   201011006         2          2  2025              0.741864
13   201011006         2          2  2026              0.741864
14   201011006         2          2  2027              0.741864
15   201011006         2          2  2025              0.741864
16   201011006         2          2  2026              0.741864
17   201011006         2          2  2027              0.741864
18   201011006         3          1  2025              0.741864
19   201011006         3          1  2026              0.741864

    distance_to_train_stop  distance_to_tram_stop  distance_to_hospital  \
0                  0.91511               1.091632              0.036647
1                  0.91511               1.091632              0.036647
2                  0.91511               1.091632              0.036647
3                  0.91511               1.091632              0.036647
4                  0.91511               1.091632              0.036647
5                  0.91511               1.091632              0.036647
6                  0.91511               1.091632              0.036647
7                  0.91511               1.091632              0.036647
8                  0.91511               1.091632              0.036647
9                  0.91511               1.091632              0.036647
10                 0.91511               1.091632              0.036647
11                 0.91511               1.091632              0.036647
12                 0.91511               1.091632              0.036647
13                 0.91511               1.091632              0.036647
14                 0.91511               1.091632              0.036647
15                 0.91511               1.091632              0.036647
16                 0.91511               1.091632              0.036647
17                 0.91511               1.091632              0.036647
18                 0.91511               1.091632              0.036647
19                 0.91511               1.091632              0.036647

    distance_to_mall  distance_to_park  distance_to_supermarket  \
0           0.007196           0.00017                 0.008238
1           0.007196           0.00017                 0.008238
2           0.007196           0.00017                 0.008238
3           0.007196           0.00017                 0.008238
4           0.007196           0.00017                 0.008238
5           0.007196           0.00017                 0.008238
6           0.007196           0.00017                 0.008238
7           0.007196           0.00017                 0.008238
8           0.007196           0.00017                 0.008238
9           0.007196           0.00017                 0.008238
10          0.007196           0.00017                 0.008238
11          0.007196           0.00017                 0.008238
12          0.007196           0.00017                 0.008238
13          0.007196           0.00017                 0.008238
14          0.007196           0.00017                 0.008238
15          0.007196           0.00017                 0.008238
16          0.007196           0.00017                 0.008238
17          0.007196           0.00017                 0.008238
18          0.007196           0.00017                 0.008238
19          0.007196           0.00017                 0.008238

    distance_to_CBD  distance_to_school  distance_to_uni  population  \
0          1.188191             0.03149         1.178579       15294
1          1.188191             0.03149         1.178579       16366
2          1.188191             0.03149         1.178579       17341
3          1.188191             0.03149         1.178579       15294
4          1.188191             0.03149         1.178579       16366
5          1.188191             0.03149         1.178579       17341
6          1.188191             0.03149         1.178579       15294
7          1.188191             0.03149         1.178579       16366
8          1.188191             0.03149         1.178579       17341
9          1.188191             0.03149         1.178579       15294
10         1.188191             0.03149         1.178579       16366
11         1.188191             0.03149         1.178579       17341
12         1.188191             0.03149         1.178579       15294
13         1.188191             0.03149         1.178579       16366
14         1.188191             0.03149         1.178579       17341
15         1.188191             0.03149         1.178579       15294
16         1.188191             0.03149         1.178579       16366
17         1.188191             0.03149         1.178579       17341
18         1.188191             0.03149         1.178579       15294
19         1.188191             0.03149         1.178579       16366

    date_numeric  bed_bath_interaction  carspaces  is_furnished        crime
0           5295                     1          1             0  1210.912850
1           5660                     1          1             0  1290.087583
2           6025                     1          1             0  1366.340312
3           5295                     1          0             0  1210.912850
4           5660                     1          0             0  1290.087583
5           6025                     1          0             0  1366.340312
6           5295                     2          1             0  1210.912850
7           5660                     2          1             0  1290.087583
8           6025                     2          1             0  1366.340312
9           5295                     2          0             0  1210.912850
10          5660                     2          0             0  1290.087583
11          6025                     2          0             0  1366.340312
12          5295                     4          1             0  1210.912850
13          5660                     4          1             0  1290.087583
14          6025                     4          1             0  1366.340312
15          5295                     4          0             0  1210.912850
16          5660                     4          0             0  1290.087583
17          6025                     4          0             0  1366.340312
18          5295                     3          1             0  1210.912850
19          5660                     3          1             0  1290.087583