This notebook uses median income data obtained from ABS to rank affordability in SA2s based on the definition that an affordable property is one where its rental price is 30% of less than the median rental income.

In [96]:
import pandas as pd

In [97]:
predicted_incomes = pd.read_csv('/Users/danielletran/Desktop/ADS_A2/project-2-group-real-estate-industry-project-34/data/landing/median_income_predictions-2011-2027-final.csv')
current_rentals = pd.read_parquet('/Users/danielletran/Desktop/ADS_A2/project-2-group-real-estate-industry-project-34/data/landing/model_data_with_income.parquet')
predicted_rentals = pd.read_csv('/Users/danielletran/Desktop/ADS_A2/project-2-group-real-estate-industry-project-34/data/landing/sa2_growth_filtered.csv')

In [98]:
current_rentals = current_rentals[current_rentals['year'] == 2024]

In [99]:
current_rentals

,bedrooms,bathrooms,propertyTypes,carspaces,latitude,longitude,price,is_furnished,year,SA2_CODE21,...,distance_to_hospital,distance_to_supermarket,distance_to_park,distance_to_mall,distance_to_CBD,distance_to_school,distance_to_uni,crime,SA2 Name,Income (Median)
1177,3.0,2.0,[apartmentUnitFlat],2.0,-38.319902,144.714149,1100.0,0,2024,214021383,...,0.030112,0.030426,0.000409,0.180564,0.561708,0.179751,0.569734,1017.453294,Point Nepean,49048.5
1240,1.0,1.0,[apartmentUnitFlat],0.0,-37.823667,144.963164,500.0,0,2024,206041509,...,0.007797,0.001226,0.001405,0.003893,0.006572,0.004837,0.015571,2893.939055,Southbank - East,56418.6
1328,1.0,1.0,[apartmentUnitFlat],1.0,-37.740287,144.899807,430.0,0,2024,206031501,...,0.000112,0.006776,0.002937,0.005959,0.102942,0.007136,0.083150,842.381376,Essendon (West) - Aberfeldie,70779.8
1329,4.0,4.0,[house],2.0,-37.814891,145.101141,1650.0,0,2024,207011147,...,0.005338,0.006951,0.002720,0.018415,0.134220,0.012162,0.035424,561.627558,Balwyn,54085.7
2158,4.0,2.0,[townhouse],2.0,-37.888028,145.126444,900.0,0,2024,212051324,...,0.010993,0.009686,0.001247,0.016478,0.174055,0.014979,0.026621,961.167090,Mount Waverley - South,56623.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120520,1.0,1.0,[house],1.0,-37.875787,145.093061,450.0,0,2024,212051319,...,0.007525,0.002800,0.001594,0.001397,0.138580,0.010002,0.035755,991.689530,Ashwood - Chadstone,59428.4
120521,2.0,2.0,[apartmentUnitFlat],1.0,-38.145125,145.122270,500.0,0,2024,214011371,...,0.001921,0.003156,0.002372,0.002429,0.361844,0.018326,0.231184,1935.735768,Frankston,56121.3
120522,1.0,1.0,[apartmentUnitFlat],0.0,-37.797417,144.979906,495.0,0,2024,206071142,...,0.004842,0.001364,0.002619,0.011134,0.024572,0.008355,0.018507,1192.870800,Fitzroy,80528.1
120524,2.0,1.0,[apartmentUnitFlat],2.0,-37.671831,145.023922,460.0,0,2024,209041529,...,0.006518,0.006668,0.001954,0.011536,0.157158,0.006750,0.055449,421.108622,Lalor - East,48868.3
120525,2.0,1.0,[apartmentUnitFlat],1.0,-37.800043,144.908201,625.0,0,2024,213031348,...,0.002993,0.005699,0.000800,0.010357,0.061535,0.017018,0.053391,1704.153100,Footscray,56291.5

In [100]:
def individual_rent(persons, rent):
    return rent/persons

In [101]:
current_rentals['price'] = current_rentals.apply(lambda row: individual_rent(row['bedrooms'], row['price']), axis = 1)

In [102]:
current_rentals = current_rentals.groupby('SA2_CODE21')['price'].median().reset_index()
current_rentals = current_rentals.rename(columns={'price': 'predicted_price_2024'})

In [103]:
current_rentals

    SA2_CODE21  predicted_price_2024
0    203021037            290.000000
1    203021040            198.333333
2    203021043            300.000000
3    203021046            205.000000
4    203031489            173.333333
..         ...                   ...
307  214021383            200.000000
308  214021384            198.333333
309  214021591            210.833333
310  214021592            275.000000
311  216021414            153.333333

[312 rows x 2 columns]

In [106]:
predicted_rentals

,SA2_CODE21,predicted_price_2025,predicted_price_2026,predicted_price_2027,actual_growth,percentage_growth,property_count,Suburb
0,212041563,513.071250,514.284250,519.777750,6.706500,1.307128,151.0,Dandenong - North
1,210051445,490.276611,494.058694,496.114806,5.838194,1.190796,245.0,Mickleham - Yuroke
2,209041528,521.927056,523.913444,526.170944,4.243889,0.813119,66.0,Doreen - South
3,207031163,559.225250,561.287750,562.160111,2.934861,0.524808,586.0,Box Hill
4,206041506,715.225972,717.795556,718.729556,3.503583,0.489857,935.0,North Melbourne
...,...,...,...,...,...,...,...,...
238,212051326,568.443667,566.806167,563.658667,-4.785000,-0.841772,2731.0,Oakleigh - Huntingdale
239,210051443,505.422278,499.853389,499.345611,-6.076667,-1.202295,57.0,Craigieburn - South
240,212031303,506.091194,505.570222,499.970083,-6.121111,-1.209488,54.0,Cranbourne South
241,213051464,492.741917,489.194000,485.792361,-6.949556,-1.410384,168.0,Point Cook - East
242,212031556,502.428611,492.100972,493.097083,-9.331528,-1.857284,59.0,Clyde North - South

In [107]:
predicted_incomes

,Statistical Areas Level 2 2021 code,Suburb,2011_Forecast,2012_Forecast,2013_Forecast,2014_Forecast,2015_Forecast,2016_Forecast,2017_Forecast,2018_Forecast,2019 Forecast,2020_Forecast,2021_Forecast,2022_Forecast,2023_Forecast,2024_Forecast,2025_Forecast,2026_Forecast,2027_Forecast
0,201011001,Alfredton,53432.300711,47374.846028,48517.071460,49263.565645,50170.087016,53590.376961,54500.946725,55590.965660,54662.184500,55741.852539,56856.689589,57993.823381,59153.699849,59748.905806,60786.125030,61580.172183,62722.058533
1,201011002,Ballarat,53427.649686,48983.463985,49079.438428,51245.827182,50976.856327,53620.920236,54496.202680,55586.126734,54693.338641,53870.515232,54947.925537,56046.884048,57167.821729,57743.045732,58745.443956,59512.833759,60616.385278
2,201011005,Buninyong,53434.168203,48096.026338,48160.656680,48454.660943,49869.710290,53939.772559,54502.851567,55592.908599,55018.568010,55790.534879,56906.345576,58044.472488,59205.361938,59801.087720,60839.212803,61633.953439,62776.837060
3,201011006,Delacombe,53433.458267,42962.681074,44104.552914,44806.359633,45933.596608,53557.352585,54502.127432,55592.169981,54628.499636,52812.981667,53869.241300,54946.626126,56045.558649,56609.490414,57592.210531,58344.535684,59426.423352
4,201011007,Smythes Creek,53427.649686,45307.819756,45709.905976,46621.391935,48000.556821,53863.034579,54496.202680,55586.126734,54940.295270,55090.746745,56192.561680,57316.412913,58462.741172,59050.994686,60076.098427,60860.870526,61989.418804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,216031415,Mooroopna,53571.079072,40905.013324,41544.442326,41330.947869,42689.099810,53542.329703,54642.500653,55735.350666,54613.176297,45549.540611,46460.531423,47389.742052,48337.536893,48823.910357,49671.475642,50320.332496,51253.426684
200,217011421,Hamilton (Vic.),53571.079072,39971.501420,41365.571457,41341.495147,42336.539038,53640.610311,54642.500653,55735.350666,54713.422517,46639.047822,47571.828778,48523.265354,49493.730661,49991.737774,50859.576118,51523.953089,52479.366116
201,217031471,Camperdown,53571.079072,39790.536268,40818.677641,40899.621919,41276.473497,53960.979567,54642.500653,55735.350666,55040.199158,48160.849843,49124.066840,50106.548176,51108.679140,51622.935904,52519.091253,53205.146415,54191.733953
202,217031472,Colac,53571.079072,41509.840339,42277.926005,43722.922133,44147.790515,53618.674486,54642.500653,55735.350666,54691.047976,48441.140993,49409.963813,50398.163090,51406.126351,51923.376037,52824.746916,53514.794849,54507.124224
203,217041479,Warrnambool - North,53571.079072,42424.804784,43074.949623,43572.942884,44305.401453,53579.578332,54642.500653,55735.350666,54651.169898,49287.998472,50273.758442,51279.233611,52304.818283,52831.110628,53748.239449,54450.350934,55460.028405

In [108]:
def get_30(yearly):
    weekly = yearly / 48 #52 weeks in a year
    proportion = weekly * 0.3

    return proportion

In [109]:
predicted_incomes_filtered = predicted_incomes[['Statistical Areas Level 2 2021 code','2024_Forecast','2025_Forecast', '2026_Forecast', '2027_Forecast']]
predicted_incomes_filtered = predicted_incomes_filtered.rename(columns={'Statistical Areas Level 2 2021 code': 'SA2_CODE21'})

In [110]:
predicted_incomes_filtered[['2024_Forecast','2025_Forecast', '2026_Forecast', '2027_Forecast']] = predicted_incomes_filtered[['2024_Forecast','2025_Forecast', '2026_Forecast', '2027_Forecast']].apply(get_30)

In [111]:
predicted_incomes_filtered

     SA2_CODE21  2024_Forecast  2025_Forecast  2026_Forecast  2027_Forecast
0     201011001     373.430661     379.913281     384.876076     392.012866
1     201011002     360.894036     367.159025     371.955211     378.852408
2     201011005     373.756798     380.245080     385.212209     392.355232
3     201011006     353.809315     359.951316     364.653348     371.415146
4     201011007     369.068717     375.475615     380.380441     387.433868
..          ...            ...            ...            ...            ...
199   216031415     305.149440     310.446723     314.502078     320.333917
200   217011421     312.448361     317.872351     322.024707     327.996038
201   217031471     322.643349     328.244320     332.532165     338.698337
202   217031472     324.521100     330.154668     334.467468     340.669526
203   217041479     330.194441     335.926497     340.314693     346.625178

[204 rows x 5 columns]

In [112]:
predicted_rentals[['SA2_CODE21','predicted_price_2025', 'predicted_price_2026','predicted_price_2027']]

,SA2_CODE21,predicted_price_2025,predicted_price_2026,predicted_price_2027
0,212041563,513.071250,514.284250,519.777750
1,210051445,490.276611,494.058694,496.114806
2,209041528,521.927056,523.913444,526.170944
3,207031163,559.225250,561.287750,562.160111
4,206041506,715.225972,717.795556,718.729556
...,...,...,...,...
238,212051326,568.443667,566.806167,563.658667
239,210051443,505.422278,499.853389,499.345611
240,212031303,506.091194,505.570222,499.970083
241,213051464,492.741917,489.194000,485.792361
242,212031556,502.428611,492.100972,493.097083

In [113]:
# Convert SA2_CODE21 to integer in both DataFrames before merging
predicted_incomes_filtered['SA2_CODE21'] = predicted_incomes_filtered['SA2_CODE21'].astype(int)
predicted_rentals['SA2_CODE21'] = predicted_rentals['SA2_CODE21'].astype(int)
current_rentals['SA2_CODE21'] = current_rentals['SA2_CODE21'].astype(int)

# Now merge the DataFrames
combined_prediction = predicted_incomes_filtered.merge(predicted_rentals, on='SA2_CODE21')
combined_prediction = combined_prediction.merge(current_rentals, on='SA2_CODE21')

# Display the merged DataFrame
print(combined_prediction.head())

   SA2_CODE21  2024_Forecast  2025_Forecast  2026_Forecast  2027_Forecast  \
0   203021037     343.322117     349.282063     353.844723     360.406096
1   203021040     381.929030     388.559179     393.634914     400.934120
2   206011106     416.773594     424.008631     429.547442     437.512577
3   206011107     390.927591     397.713952     402.909276     410.380457
4   206011109     423.387991     430.737852     436.364567     444.456112

   predicted_price_2025  predicted_price_2026  predicted_price_2027  \
0            488.685139            489.172917            488.943889
1            497.425361            497.425361            497.368139
2            687.696444            687.863250            688.768806
3            627.613611            627.613611            627.613611
4            600.392889            600.392889            600.526222

   actual_growth  percentage_growth  property_count  \
0       0.258750           0.052948           568.0
1      -0.057222          -0.011504          1283.0
2       1.072361           0.155935           428.0
3       0.000000           0.000000           727.0
4       0.133333           0.022208           180.0

                          Suburb  predicted_price_2024
0                        Belmont            290.000000
1  Geelong West - Hamlyn Heights            198.333333
2                 Brunswick East            380.000000
3                 Brunswick West            325.000000
4              Pascoe Vale South            216.666667

In [114]:
combined_prediction = predicted_incomes_filtered.merge(predicted_rentals,on='SA2_CODE21')
combined_prediction = combined_prediction.merge(current_rentals, on = 'SA2_CODE21')

In [115]:
combined_prediction

,SA2_CODE21,2024_Forecast,2025_Forecast,2026_Forecast,2027_Forecast,predicted_price_2025,predicted_price_2026,predicted_price_2027,actual_growth,percentage_growth,property_count,Suburb,predicted_price_2024
0,203021037,343.322117,349.282063,353.844723,360.406096,488.685139,489.172917,488.943889,0.258750,0.052948,568.0,Belmont,290.000000
1,203021040,381.929030,388.559179,393.634914,400.934120,497.425361,497.425361,497.368139,-0.057222,-0.011504,1283.0,Geelong West - Hamlyn Heights,198.333333
2,206011106,416.773594,424.008631,429.547442,437.512577,687.696444,687.863250,688.768806,1.072361,0.155935,428.0,Brunswick East,380.000000
3,206011107,390.927591,397.713952,402.909276,410.380457,627.613611,627.613611,627.613611,0.000000,0.000000,727.0,Brunswick West,325.000000
4,206011109,423.387991,430.737852,436.364567,444.456112,600.392889,600.392889,600.526222,0.133333,0.022208,180.0,Pascoe Vale South,216.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,213031351,383.557182,390.215595,395.312968,402.643290,531.574722,531.574722,531.587500,0.012778,0.002404,168.0,West Footscray - Tottenham,280.000000
101,213051363,343.164364,349.121572,353.682136,360.240494,485.856194,486.241417,486.647806,0.791611,0.162931,93.0,Laverton,156.250000
102,213051464,397.875132,404.782099,410.069754,417.673713,492.741917,489.194000,485.792361,-6.949556,-1.410384,168.0,Point Cook - East,135.000000
103,213051466,428.235791,435.669808,441.360948,449.545142,487.928639,488.226139,488.656139,0.727500,0.149100,189.0,Point Cook - South,137.500000
104,214011371,348.520662,354.570853,359.202601,365.863325,500.111417,500.159194,499.925083,-0.186333,-0.037258,81.0,Frankston,215.000000

In [116]:
def calculate_affordability(weekly_rent, weekly_income_proportion):
    difference = weekly_rent - weekly_income_proportion

    #if difference is positive, rent is more than 30% of the income

    #if difference is negative, rent is less than 30% of the income

    return difference

In [117]:
combined_prediction['2024_affordability_difference'] = combined_prediction.apply(
    lambda row: calculate_affordability(row['predicted_price_2024'], row['2024_Forecast']), axis=1)

combined_prediction['2025_affordability_difference'] = combined_prediction.apply(
    lambda row: calculate_affordability(row['predicted_price_2025'], row['2025_Forecast']), axis=1)

combined_prediction['2026_affordability_difference'] = combined_prediction.apply(
    lambda row: calculate_affordability(row['predicted_price_2026'], row['2026_Forecast']), axis=1)

combined_prediction['2027_affordability_difference'] = combined_prediction.apply(
    lambda row: calculate_affordability(row['predicted_price_2027'], row['2027_Forecast']), axis=1)

In [118]:
tfouraffordability = combined_prediction[['SA2_CODE21','Suburb','2024_affordability_difference']].sort_values(by='2024_affordability_difference')
tfiveaffordability = combined_prediction[['SA2_CODE21','Suburb','2025_affordability_difference']].sort_values(by='2025_affordability_difference')
tsixaffordability = combined_prediction[['SA2_CODE21','Suburb','2026_affordability_difference']].sort_values(by='2026_affordability_difference')
tsevenaffordability = combined_prediction[['SA2_CODE21','Suburb','2027_affordability_difference']].sort_values(by='2027_affordability_difference')

In [119]:
# List of suburbs to remove
suburbs_to_remove = ['Torquay', 'Highton', 'Geelong West - Hamlyn Heights', 'Geelong', 'North Geelong - Bell Park', 'Leopold', 'Newcomb']

tfouraffordability = tfouraffordability[~tfouraffordability['Suburb'].isin(suburbs_to_remove)]

# Filter out rows where 'Suburb' is in the list for tfiveaffordability
tfiveaffordability = tfiveaffordability[~tfiveaffordability['Suburb'].isin(suburbs_to_remove)]

# Filter out rows where 'Suburb' is in the list for tsixaffordability
tsixaffordability = tsixaffordability[~tsixaffordability['Suburb'].isin(suburbs_to_remove)]

# Filter out rows where 'Suburb' is in the list for tsevenaffordability
tsevenaffordability = tsevenaffordability[~tsevenaffordability['Suburb'].isin(suburbs_to_remove)]

In [120]:
tfouraffordability.to_csv('data/landing/2024_affordability_rankings', index = False)

In [121]:
tfiveaffordability.to_csv('data/landing/2025_affordability_rankings',index = False)

OSError: Cannot save file into a non-existent directory: 'data/landing'

In [ ]:
tsixaffordability.to_csv('data/landing/2026_affordability_rankings',index = False)

In [ ]:
tsevenaffordability.to_csv('data/landing/2027_affordability_rankings',index = False)

In [ ]:
combined_prediction

,SA2_CODE21,2025_Forecast,2026_Forecast,2027_Forecast,predicted_price_2025,predicted_price_2026,predicted_price_2027,actual_growth,percentage_growth,property_count,Suburb,2025_affordability_difference,2026_affordability_difference,2027_affordability_difference
0,203021037,349.282063,353.844723,360.406096,488.685139,489.172917,488.943889,0.258750,0.052948,568.0,Belmont,139.403076,135.328193,128.537793
1,203021039,366.202626,370.986319,377.865550,510.810889,510.810889,510.987694,0.176806,0.034613,1473.0,Geelong,144.608263,139.824570,133.122145
2,203021040,388.559179,393.634914,400.934120,497.425361,497.425361,497.368139,-0.057222,-0.011504,1283.0,Geelong West - Hamlyn Heights,108.866183,103.790447,96.434019
3,203021042,378.094013,383.033043,390.135657,482.487917,482.555694,481.706806,-0.781111,-0.161892,338.0,Highton,104.393903,99.522652,91.571149
4,203021044,355.898041,360.547126,367.232781,510.008944,510.087278,510.113111,0.104167,0.020424,183.0,Leopold,154.110903,149.540152,142.880330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,213031351,390.215595,395.312968,402.643290,531.574722,531.574722,531.587500,0.012778,0.002404,168.0,West Footscray - Tottenham,141.359127,136.261754,128.944210
115,213051363,349.121572,353.682136,360.240494,485.856194,486.241417,486.647806,0.791611,0.162931,93.0,Laverton,136.734622,132.559281,126.407312
116,213051464,404.782099,410.069754,417.673713,492.741917,489.194000,485.792361,-6.949556,-1.410384,168.0,Point Cook - East,87.959817,79.124246,68.118648
117,213051466,435.669808,441.360948,449.545142,487.928639,488.226139,488.656139,0.727500,0.149100,189.0,Point Cook - South,52.258831,46.865191,39.110997
118,214011371,354.570853,359.202601,365.863325,500.111417,500.159194,499.925083,-0.186333,-0.037258,81.0,Frankston,145.540563,140.956594,134.061758